"use client";

import "./globals.css";
import { Lato } from "next/font/google";
import Footer from "../components/Footer/Footer";
import { useState } from "react";
import useDarkMode from "../hooks/useDarkMode";
import { ThemeProvider } from "styled-components";
import lightTheme, { darkTheme } from "../theming/themeContext";
import { Body, Midi, Heading, Full, Paragraph, Paragraph2, GlobalStyles2 } from "../theming/styles";
import { Spread } from "../components/switch/styles";
import Navbar from "../components/Navbar/Navbar";
import GlobalStyles from "@/theming/global";

const lato = Lato({
    weight: ["400", "700", "900"],
    subsets: ["latin"]
});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app"
// };

export default function RootLayout({ children }) {
    const [darkMode, setDarkMode] = useState(false);

    const [mode, toggleMode, spread, setDisableScroll] = useDarkMode();

    const spreadClass = spread === "first" ? "growBlack" : spread === "second" ? "growWhite" : "";

    return (
        <html lang="en">
            <ThemeProvider theme={mode === "light" ? lightTheme : darkTheme}>
                {/* <Body
                //     className={`${lato.className} relative
                //     ${darkMode ? "text-white" : "text-black"}
                //     overflow-x-hidden
                //     `
                // }
            > */}
                <Body
                    style={{
                        position: "relative",
                        height: setDisableScroll ? "100vh" : "unset"
                    }}
                    className={lato.className}
                >
                    <Spread className={spreadClass} />
                    <Navbar mode={mode} toggleMode={toggleMode} />
                    {children}
                    <Footer />
                    {/* </Body> */}
                </Body>
            </ThemeProvider>
        </html>
    );
}
